# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cucover}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Wynne"]
  s.date = %q{2009-06-23}
  s.default_executable = %q{cucover}
  s.description = %q{Lazy coverage-aware running of Cucumber acceptance tests}
  s.email = %q{matt@mattwynne.net}
  s.executables = ["cucover"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "Licence.txt",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bin/cucover",
     "cucover.gemspec",
     "examples/self_test/rails/.gitignore",
     "examples/self_test/rails/README",
     "examples/self_test/rails/Rakefile",
     "examples/self_test/rails/app/controllers/application.rb",
     "examples/self_test/rails/app/controllers/widgets_controller.rb",
     "examples/self_test/rails/app/views/widgets/index.html.erb",
     "examples/self_test/rails/config/boot.rb",
     "examples/self_test/rails/config/database.yml",
     "examples/self_test/rails/config/environment.rb",
     "examples/self_test/rails/config/environments/development.rb",
     "examples/self_test/rails/config/environments/production.rb",
     "examples/self_test/rails/config/environments/test.rb",
     "examples/self_test/rails/config/routes.rb",
     "examples/self_test/rails/db/test.sqlite3",
     "examples/self_test/rails/features/see_widgets.feature",
     "examples/self_test/rails/features/step_definitions/env.rb",
     "examples/self_test/rails/features/step_definitions/webrat_steps.rb",
     "examples/self_test/rails/features/support/env.rb",
     "examples/self_test/rails/lib/tasks/cucumber.rake",
     "examples/self_test/rails/public/404.html",
     "examples/self_test/rails/public/422.html",
     "examples/self_test/rails/public/500.html",
     "examples/self_test/rails/public/dispatch.cgi",
     "examples/self_test/rails/public/dispatch.fcgi",
     "examples/self_test/rails/public/dispatch.rb",
     "examples/self_test/rails/public/favicon.ico",
     "examples/self_test/rails/public/images/rails.png",
     "examples/self_test/rails/public/index.html",
     "examples/self_test/rails/public/javascripts/application.js",
     "examples/self_test/rails/public/javascripts/controls.js",
     "examples/self_test/rails/public/javascripts/dragdrop.js",
     "examples/self_test/rails/public/javascripts/effects.js",
     "examples/self_test/rails/public/javascripts/prototype.js",
     "examples/self_test/rails/public/robots.txt",
     "examples/self_test/rails/script/about",
     "examples/self_test/rails/script/console",
     "examples/self_test/rails/script/cucumber",
     "examples/self_test/rails/script/dbconsole",
     "examples/self_test/rails/script/destroy",
     "examples/self_test/rails/script/generate",
     "examples/self_test/rails/script/performance/benchmarker",
     "examples/self_test/rails/script/performance/profiler",
     "examples/self_test/rails/script/performance/request",
     "examples/self_test/rails/script/plugin",
     "examples/self_test/rails/script/process/inspector",
     "examples/self_test/rails/script/process/reaper",
     "examples/self_test/rails/script/process/spawner",
     "examples/self_test/rails/script/runner",
     "examples/self_test/rails/script/server",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/.specification",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/History.txt",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/MIT-LICENSE.txt",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/README.rdoc",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/Rakefile",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/install.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/configuration.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/elements/area.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/elements/element.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/elements/field.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/elements/form.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/elements/label.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/elements/link.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/elements/select_option.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/locators.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/locators/area_locator.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/locators/button_locator.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/locators/field_by_id_locator.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/locators/field_labeled_locator.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/locators/field_locator.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/locators/field_named_locator.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/locators/form_locator.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/locators/label_locator.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/locators/link_locator.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/locators/locator.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/locators/select_option_locator.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/logging.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/matchers.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/matchers/have_content.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/matchers/have_selector.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/matchers/have_tag.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/matchers/have_xpath.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/methods.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/mime.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/save_and_open_page.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/scope.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/session.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/xml.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/xml/hpricot.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/xml/nokogiri.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/xml/rexml.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core_extensions/blank.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core_extensions/deprecate.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core_extensions/detect_mapped.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core_extensions/meta_class.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core_extensions/nil_to_param.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core_extensions/tcp_socket.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/mechanize.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/merb.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/merb_session.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/rack.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/rails.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/rspec-rails.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/application_server.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/location_strategy_javascript/button.js",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/location_strategy_javascript/label.js",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/location_strategy_javascript/webrat.js",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/location_strategy_javascript/webratlink.js",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/location_strategy_javascript/webratlinkwithin.js",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/location_strategy_javascript/webratselectwithoption.js",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/matchers.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/matchers/have_content.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/matchers/have_selector.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/matchers/have_tag.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/matchers/have_xpath.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/merb_application_server.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/rails_application_server.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/selenium_extensions.js",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/selenium_rc_server.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/selenium_session.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/sinatra_application_server.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/sinatra.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/vendor/selenium-server.jar",
     "examples/self_test/simple/features/call_foo.feature",
     "examples/self_test/simple/features/call_foo_and_bar_together.feature",
     "examples/self_test/simple/features/call_foo_from_background_then_bar.feature",
     "examples/self_test/simple/features/call_foo_from_background_then_bar_then_baz.feature",
     "examples/self_test/simple/features/call_foo_then_bar.feature",
     "examples/self_test/simple/features/call_foo_then_bar_from_scenario_outline_examples.feature",
     "examples/self_test/simple/features/fail.feature",
     "examples/self_test/simple/features/step_definitions/main_steps.rb",
     "examples/self_test/simple/lib/bar.rb",
     "examples/self_test/simple/lib/baz.rb",
     "examples/self_test/simple/lib/foo.rb",
     "features/call_foo.feature",
     "features/coverage_of.feature",
     "features/fail.feature",
     "features/lazy_run.feature",
     "features/lazy_run_per_scenario.feature",
     "features/lazy_run_per_scenario_outline_example.feature",
     "features/lazy_run_triggered_by_rails_view_change.feature",
     "features/run.feature",
     "features/show_recordings.feature",
     "features/step_definitions/main_steps.rb",
     "features/support/env.rb",
     "lib/cucover.rb",
     "lib/cucover/cli.rb",
     "lib/cucover/cli_commands/coverage_of.rb",
     "lib/cucover/cli_commands/cucumber.rb",
     "lib/cucover/cli_commands/show_recordings.rb",
     "lib/cucover/cli_commands/version.rb",
     "lib/cucover/controller.rb",
     "lib/cucover/cucumber_hooks.rb",
     "lib/cucover/logging_config.rb",
     "lib/cucover/monkey.rb",
     "lib/cucover/rails.rb",
     "lib/cucover/recorder.rb",
     "lib/cucover/recording.rb",
     "lib/cucover/recording/covered_file.rb",
     "lib/cucover/store.rb",
     "lib/dependencies.rb",
     "spec/cucover/cli_spec.rb",
     "spec/cucover/controller_spec.rb",
     "spec/cucover/recording/covered_file_spec.rb",
     "spec/cucover/store_spec.rb",
     "spec/spec_helper.rb",
     "tmp/.gitignore"
  ]
  s.has_rdoc = true
  s.homepage = %q{http://github.com/mattwynne/cucover/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.1}
  s.summary = %q{Lazy coverage-aware running of Cucumber acceptance tests}
  s.test_files = [
    "spec/cucover/cli_spec.rb",
     "spec/cucover/controller_spec.rb",
     "spec/cucover/recording/covered_file_spec.rb",
     "spec/cucover/store_spec.rb",
     "spec/spec_helper.rb",
     "examples/self_test/rails/app/controllers/application.rb",
     "examples/self_test/rails/app/controllers/widgets_controller.rb",
     "examples/self_test/rails/config/boot.rb",
     "examples/self_test/rails/config/environment.rb",
     "examples/self_test/rails/config/environments/development.rb",
     "examples/self_test/rails/config/environments/production.rb",
     "examples/self_test/rails/config/environments/test.rb",
     "examples/self_test/rails/config/routes.rb",
     "examples/self_test/rails/features/step_definitions/env.rb",
     "examples/self_test/rails/features/step_definitions/webrat_steps.rb",
     "examples/self_test/rails/features/support/env.rb",
     "examples/self_test/rails/public/dispatch.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/install.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/configuration.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/elements/area.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/elements/element.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/elements/field.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/elements/form.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/elements/label.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/elements/link.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/elements/select_option.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/locators/area_locator.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/locators/button_locator.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/locators/field_by_id_locator.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/locators/field_labeled_locator.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/locators/field_locator.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/locators/field_named_locator.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/locators/form_locator.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/locators/label_locator.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/locators/link_locator.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/locators/locator.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/locators/select_option_locator.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/locators.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/logging.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/matchers/have_content.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/matchers/have_selector.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/matchers/have_tag.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/matchers/have_xpath.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/matchers.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/methods.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/mime.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/save_and_open_page.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/scope.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/session.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/xml/hpricot.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/xml/nokogiri.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/xml/rexml.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core/xml.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core_extensions/blank.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core_extensions/deprecate.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core_extensions/detect_mapped.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core_extensions/meta_class.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core_extensions/nil_to_param.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/core_extensions/tcp_socket.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/mechanize.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/merb.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/merb_session.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/rack.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/rails.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/rspec-rails.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/application_server.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/matchers/have_content.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/matchers/have_selector.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/matchers/have_tag.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/matchers/have_xpath.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/matchers.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/merb_application_server.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/rails_application_server.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/selenium_rc_server.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/selenium_session.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium/sinatra_application_server.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/selenium.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat/sinatra.rb",
     "examples/self_test/rails/vendor/gems/webrat-0.4.4/lib/webrat.rb",
     "examples/self_test/simple/features/step_definitions/main_steps.rb",
     "examples/self_test/simple/lib/bar.rb",
     "examples/self_test/simple/lib/baz.rb",
     "examples/self_test/simple/lib/foo.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<cucumber>, [">= 0.3.11"])
      s.add_runtime_dependency(%q<relevance-rcov>, [">= 0.8.3.4"])
      s.add_runtime_dependency(%q<logging>, [">= 1.1.4"])
    else
      s.add_dependency(%q<cucumber>, [">= 0.3.11"])
      s.add_dependency(%q<relevance-rcov>, [">= 0.8.3.4"])
      s.add_dependency(%q<logging>, [">= 1.1.4"])
    end
  else
    s.add_dependency(%q<cucumber>, [">= 0.3.11"])
    s.add_dependency(%q<relevance-rcov>, [">= 0.8.3.4"])
    s.add_dependency(%q<logging>, [">= 1.1.4"])
  end
end
