# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cucover}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Wynne", "Joseph Wilk"]
  s.date = %q{2010-04-08}
  s.default_executable = %q{cucover}
  s.description = %q{Lazy coverage-aware running of Cucumber acceptance tests}
  s.email = %q{matt@mattwynne.net}
  s.executables = ["cucover"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "Licence.txt",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bin/cucover",
     "cucover.gemspec",
     "cucumber.yml",
     "examples/self_test/rails/.gitignore",
     "examples/self_test/rails/Rakefile",
     "examples/self_test/rails/app/controllers/application_controller.rb",
     "examples/self_test/rails/app/controllers/widgets_controller.rb",
     "examples/self_test/rails/app/helpers/application_helper.rb",
     "examples/self_test/rails/app/views/widgets/index.html.erb",
     "examples/self_test/rails/config/boot.rb",
     "examples/self_test/rails/config/cucumber.yml",
     "examples/self_test/rails/config/database.yml",
     "examples/self_test/rails/config/environment.rb",
     "examples/self_test/rails/config/environments/cucumber.rb",
     "examples/self_test/rails/config/environments/development.rb",
     "examples/self_test/rails/config/environments/production.rb",
     "examples/self_test/rails/config/environments/test.rb",
     "examples/self_test/rails/config/initializers/backtrace_silencers.rb",
     "examples/self_test/rails/config/initializers/inflections.rb",
     "examples/self_test/rails/config/initializers/mime_types.rb",
     "examples/self_test/rails/config/initializers/new_rails_defaults.rb",
     "examples/self_test/rails/config/initializers/session_store.rb",
     "examples/self_test/rails/config/locales/en.yml",
     "examples/self_test/rails/config/routes.rb",
     "examples/self_test/rails/db/seeds.rb",
     "examples/self_test/rails/db/test.sqlite3",
     "examples/self_test/rails/features/see_widgets.feature",
     "examples/self_test/rails/features/step_definitions/web_steps.rb",
     "examples/self_test/rails/features/support/env.rb",
     "examples/self_test/rails/features/support/paths.rb",
     "examples/self_test/rails/lib/tasks/cucumber.rake",
     "examples/self_test/rails/public/404.html",
     "examples/self_test/rails/public/422.html",
     "examples/self_test/rails/public/500.html",
     "examples/self_test/rails/public/favicon.ico",
     "examples/self_test/rails/public/images/rails.png",
     "examples/self_test/rails/public/index.html",
     "examples/self_test/rails/public/javascripts/application.js",
     "examples/self_test/rails/public/javascripts/controls.js",
     "examples/self_test/rails/public/javascripts/dragdrop.js",
     "examples/self_test/rails/public/javascripts/effects.js",
     "examples/self_test/rails/public/javascripts/prototype.js",
     "examples/self_test/rails/public/robots.txt",
     "examples/self_test/rails/script/about",
     "examples/self_test/rails/script/console",
     "examples/self_test/rails/script/cucumber",
     "examples/self_test/rails/script/dbconsole",
     "examples/self_test/rails/script/destroy",
     "examples/self_test/rails/script/generate",
     "examples/self_test/rails/script/performance/benchmarker",
     "examples/self_test/rails/script/performance/profiler",
     "examples/self_test/rails/script/plugin",
     "examples/self_test/rails/script/runner",
     "examples/self_test/rails/script/server",
     "examples/self_test/simple/features/call_foo.feature",
     "examples/self_test/simple/features/call_foo_and_bar_together.feature",
     "examples/self_test/simple/features/call_foo_from_background_then_bar.feature",
     "examples/self_test/simple/features/call_foo_from_background_then_bar_then_baz.feature",
     "examples/self_test/simple/features/call_foo_then_bar.feature",
     "examples/self_test/simple/features/call_foo_then_bar_from_scenario_outline_examples.feature",
     "examples/self_test/simple/features/fail.feature",
     "examples/self_test/simple/features/step_definitions/main_steps.rb",
     "examples/self_test/simple/lib/bar.rb",
     "examples/self_test/simple/lib/baz.rb",
     "examples/self_test/simple/lib/foo.rb",
     "features/call_foo.feature",
     "features/coverage_of.feature",
     "features/fail.feature",
     "features/help.feature",
     "features/lazy_run.feature",
     "features/lazy_run_per_scenario.feature",
     "features/lazy_run_per_scenario_outline_example.feature",
     "features/lazy_run_triggered_by_rails_view_change.feature",
     "features/run.feature",
     "features/show_recordings.feature",
     "features/step_definitions/main_steps.rb",
     "features/support/env.rb",
     "lib/at_exit_hook.rb",
     "lib/cucover.rb",
     "lib/cucover/cli.rb",
     "lib/cucover/cli_commands/coverage_of.rb",
     "lib/cucover/cli_commands/cucumber.rb",
     "lib/cucover/cli_commands/show_recordings.rb",
     "lib/cucover/cli_commands/version.rb",
     "lib/cucover/controller.rb",
     "lib/cucover/cucumber_hooks.rb",
     "lib/cucover/line_numbers.rb",
     "lib/cucover/logging_config.rb",
     "lib/cucover/monkey.rb",
     "lib/cucover/rails.rb",
     "lib/cucover/recorder.rb",
     "lib/cucover/recording.rb",
     "lib/cucover/recording/covered_file.rb",
     "lib/cucover/store.rb",
     "lib/dependencies.rb",
     "spec/cucover/cli_spec.rb",
     "spec/cucover/controller_spec.rb",
     "spec/cucover/recording/covered_file_spec.rb",
     "spec/cucover/store_spec.rb",
     "spec/spec_helper.rb",
     "tmp/.gitignore"
  ]
  s.homepage = %q{http://github.com/mattwynne/cucover/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Lazy coverage-aware running of Cucumber acceptance tests}
  s.test_files = [
    "spec/cucover/cli_spec.rb",
     "spec/cucover/controller_spec.rb",
     "spec/cucover/recording/covered_file_spec.rb",
     "spec/cucover/store_spec.rb",
     "spec/spec_helper.rb",
     "examples/self_test/rails/app/controllers/application_controller.rb",
     "examples/self_test/rails/app/controllers/widgets_controller.rb",
     "examples/self_test/rails/app/helpers/application_helper.rb",
     "examples/self_test/rails/config/boot.rb",
     "examples/self_test/rails/config/environment.rb",
     "examples/self_test/rails/config/environments/cucumber.rb",
     "examples/self_test/rails/config/environments/development.rb",
     "examples/self_test/rails/config/environments/production.rb",
     "examples/self_test/rails/config/environments/test.rb",
     "examples/self_test/rails/config/initializers/backtrace_silencers.rb",
     "examples/self_test/rails/config/initializers/inflections.rb",
     "examples/self_test/rails/config/initializers/mime_types.rb",
     "examples/self_test/rails/config/initializers/new_rails_defaults.rb",
     "examples/self_test/rails/config/initializers/session_store.rb",
     "examples/self_test/rails/config/routes.rb",
     "examples/self_test/rails/db/seeds.rb",
     "examples/self_test/rails/features/step_definitions/web_steps.rb",
     "examples/self_test/rails/features/support/env.rb",
     "examples/self_test/rails/features/support/paths.rb",
     "examples/self_test/simple/features/step_definitions/main_steps.rb",
     "examples/self_test/simple/lib/bar.rb",
     "examples/self_test/simple/lib/baz.rb",
     "examples/self_test/simple/lib/foo.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<cucumber>, [">= 0.6.4"])
      s.add_runtime_dependency(%q<rcov>, [">= 0.9.8"])
      s.add_runtime_dependency(%q<logging>, [">= 1.4.1"])
    else
      s.add_dependency(%q<cucumber>, [">= 0.6.4"])
      s.add_dependency(%q<rcov>, [">= 0.9.8"])
      s.add_dependency(%q<logging>, [">= 1.4.1"])
    end
  else
    s.add_dependency(%q<cucumber>, [">= 0.6.4"])
    s.add_dependency(%q<rcov>, [">= 0.9.8"])
    s.add_dependency(%q<logging>, [">= 1.4.1"])
  end
end
